spring.application.name=demo_3001
server.port=3000

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/webbanhang
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Momo Payment Config (Sandbox)
momo.momo-api-url=https://test-payment.momo.vn/v2/gateway/api/create
momo.secret-key=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.access-key=F8BBA842ECF85
momo.return-url=http://localhost:3000/payment/momo-return
momo.notify-url=http://localhost:3000/payment/momo-notify
momo.partner-code=MOMO
momo.partner-name=Demo3001
momo.store-id=Demo3001Store
momo.request-type=captureWallet

# Mail Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=buiquy845@gmail.com
spring.mail.password=oqaq mowe sfgv apml
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OTP Verification
app.auth.otp.expire-minutes=2
